export const retailerList = [
  "Austin Foil Alliance",
  "Big Winds",
  "Blue Planet Surf",
  "Boost Kiteboarding",
  "Capt Kirk's Watersports",
  "Covewater Paddle Surf",
  "Curtis Sport Connection",
  "Deuxieme Vague",
  "Dirty Mermaid Watersports",
  "East of Maui Surf Shop",
  "Element Watersports",
  "Elite Water Sports",
  "Epic Boardsports",
  "Explore Kiteboarding",
  "Extreme Windsurfing",
  "Floras Lake Kite & Windsurf",
  "Good Breeze Kiteboarding",
  "Gorge Performance",
  "Green Hat Kiteboarding",
  "Gulfport Boardsports",
  "Half Life",
  "Hampton Watersports",
  "Hawaiian watersports",
  "Houston Kiteboarding",
  "Inland Sea Windsurf Co.",
  "Island Surf & Sail",
  "Isthmus Sailboards",
  "Jupiter Kiteboarding",
  "Kite Paddle Surf",
  "Kite Zombies",
  "Kite-Line",
  "Kiteboarding.com",
  "Kiteforce",
  "Kiteriders LLC",
  "Liquid Surf & Sail",
  "Mac Kiteboarding",
  "Miami Kiteboarding",
  "Murray's Marine",
  "NY Kite Center",
  "No Limit Kiteboarding",
  "North Beach Windsurfing",
  "North Shore Ski & Board",
  "Northline Sports",
  "Ocean Air Sports",
  "Otherside Boardsports",
  "PB Kiteboarding",
  "Poseidon Paddle & Surf",
  "Real Watersports",
  "Sailsport Marine",
  "Sandy Point Progressive Sports",
  "Session Sports",
  "Silent Sports",
  "Solstice Sports",
  "Stand Up Outfitters, LLC",
  "Superior Kiteboarding",
  "Urban Surf",
  "Ventura Salt Co",
  "WINDANCE Boardshop LLC",
  "Wind NC",
  "Wind Spirit"
]